# Generated by Django 5.2.7 on 2025-10-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamificationprofile',
            name='current_streaks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamificationprofile',
            name='last_login_data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
