# Generated by Django 5.2.7 on 2025-11-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_gamificationprofile_current_streaks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='slug',
            field=models.SlugField(default='temp-slug', help_text='Unique Identifier', unique=True),
            preserve_default=False,
        ),
    ]
