# Generated by Django 5.2.7 on 2025-11-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_badge_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamificationprofile',
            name='badges',
            field=models.ManyToManyField(blank=True, to='users.badge'),
        ),
    ]
